#include "SfzExporter.h"
#include "../separation/AnalysisUtils.h"
#include <cmath>

namespace afq
{
    namespace
    {
        juce::String sanitizeForFilename (const juce::String& s)
        {
            return s.retainCharacters ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_- ")
                    .replace (" ", "_");
        }

        int detectRootMidiNote (const juce::AudioBuffer<float>& buffer, int64_t start, int64_t end, double sampleRate)
        {
            const int len = (int) (end - start);
            if (len <= 0) return 60;

            juce::AudioBuffer<float> mono (1, len);
            mono.clear();
            const float scale = 1.0f / (float) juce::jmax (1, buffer.getNumChannels());
            for (int ch = 0; ch < buffer.getNumChannels(); ++ch)
                mono.addFrom (0, 0, buffer, ch, (int) start, len, scale);

            const auto pitch = estimatePitch (mono.getReadPointer (0), len, sampleRate);
            if (pitch.confidence < 0.2f || pitch.hz <= 0.0f)
                return 60; // low-confidence (noisy/percussive) — default to middle C rather than guess wildly

            const double midi = 69.0 + 12.0 * std::log2 (pitch.hz / 440.0);
            return juce::jlimit (0, 127, (int) std::lround (midi));
        }
    }

    bool SfzExporter::exportOneShot (const juce::AudioBuffer<float>& sourceBuffer, int64_t startSample, int64_t endSample,
                                      double sampleRate, const Settings& settings, juce::String& errorMessage)
    {
        const int len = (int) (endSample - startSample);
        if (len <= 0)
        {
            errorMessage = "Empty sample range.";
            return false;
        }

        const juce::String safeName = sanitizeForFilename (settings.prefix + settings.instrumentName);
        const juce::File instrumentFolder = settings.destinationFolder.getChildFile (safeName);
        if (! instrumentFolder.createDirectory())
        {
            errorMessage = "Could not create folder: " + instrumentFolder.getFullPathName();
            return false;
        }

        const juce::String wavFileName = safeName + ".wav";
        const juce::File wavFile = instrumentFolder.getChildFile (wavFileName);
        wavFile.deleteFile();

        {
            std::unique_ptr<juce::FileOutputStream> stream (wavFile.createOutputStream());
            if (stream == nullptr)
            {
                errorMessage = "Could not open " + wavFile.getFullPathName() + " for writing.";
                return false;
            }

            juce::WavAudioFormat wavFormat;
            std::unique_ptr<juce::AudioFormatWriter> writer (
                wavFormat.createWriterFor (stream.get(), sampleRate, (unsigned int) sourceBuffer.getNumChannels(),
                                            24, settings.metadata, 0));
            if (writer == nullptr)
            {
                errorMessage = "Could not create WAV writer for " + wavFile.getFullPathName();
                return false;
            }
            stream.release();

            juce::AudioBuffer<float> slice (sourceBuffer.getNumChannels(), len);
            for (int ch = 0; ch < sourceBuffer.getNumChannels(); ++ch)
                slice.copyFrom (ch, 0, sourceBuffer, ch, (int) startSample, len);

            if (! writer->writeFromAudioSampleBuffer (slice, 0, len))
            {
                errorMessage = "Failed writing audio to " + wavFile.getFullPathName();
                return false;
            }
        }

        const int rootKey = settings.rootKeyOverride >= 0
                                 ? juce::jlimit (0, 127, settings.rootKeyOverride)
                                 : detectRootMidiNote (sourceBuffer, startSample, endSample, sampleRate);

        juce::String sfz;
        sfz << "// Generated by AkwardFreQ — see docs/FEATURE_SPEC.md for provenance.\n"
            << "<group>\n"
            << "amp_veltrack=0\n" // one-shot: full volume regardless of velocity by default, easy to tweak in-sampler
            << "\n"
            << "<region>\n"
            << "sample=" << wavFileName << "\n"
            << "lokey=" << settings.lowKey << "\n"
            << "hikey=" << settings.highKey << "\n"
            << "pitch_keycenter=" << rootKey << "\n"
            << "lovel=0\n"
            << "hivel=127\n";

        const juce::File sfzFile = instrumentFolder.getChildFile (safeName + ".sfz");
        if (! sfzFile.replaceWithText (sfz))
        {
            errorMessage = "Could not write " + sfzFile.getFullPathName();
            return false;
        }

        return true;
    }
}
