"""
sound_forge/chopper/export/sfz_exporter.py — SFZ instrument exporter.
"""
import os


class SfzExporter:
    def export(self, slices: list, output_dir: str, instrument_name: str) -> str:
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, "samples"), exist_ok=True)
        sfz_path = os.path.join(output_dir, f"{instrument_name}.sfz")

        lines = [
            f"// {instrument_name} — generated by KNTKTA sound_forge",
            f"// {len(slices)} slices",
            "",
            "<control>",
            "default_path=samples/",
            "",
        ]
        for slc in slices:
            wav_name = os.path.basename(slc.filename) if slc.filename else f"slice_{slc.index:03d}.wav"
            lines += [
                "<group>",
                "<region>",
                f"  sample={wav_name}",
                f"  lokey={slc.midi_note}",
                f"  hikey={slc.midi_note}",
                f"  pitch_keycenter={slc.midi_note}",
                "  lovel=0 hivel=127",
                "",
            ]

        with open(sfz_path, "w") as f:
            f.write("\n".join(lines))
        return sfz_path
